version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: mypostgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - mynetwork
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  mongodb:
    image: mongo:latest
    container_name: mymongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    networks:
      - mynetwork
    volumes:
      - mongo_data:/data/db
  
  redis:
    image: "redis:latest"
    container_name: redis_db
    networks:
      - mynetwork
    ports:
      - "6379:6379"

volumes:
   mongo_data:
   mysql_data:

networks:
  mynetwork:
    external: true
